url: https://montyhacks.toogoodbruh.com   # with the https protocol
enforce_ssl: montyhacks.toogoodbruh.com   # without any protocol

# For example, my configuration is this:
url: https://toogoodbruh.com/
enforce_ssl: toogoodbruh.com
